# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsM7nvy69bQ6kxfNJwqfzaeS8IQRXOyF
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import joblib

data='/content/drive/MyDrive/Mall_Customers.csv'
df=pd.read_csv(data)
print(df.info)
print(df.shape)
print(df.describe())
print(df.isnull().sum())
#The Mall Customers dataset contains no missing values, so no imputation was required.

df.columns

df.rename(columns={
    'Annual Income (k$)': 'Income',
    'Spending Score (1-100)': 'SpendingScore',
    'Genre': 'Gender'
}, inplace=True)

df.head()

df = pd.get_dummies(df, columns=['Gender'], drop_first=True)

sns.countplot(x='Gender_Male', data=df)
plt.title("Gender Distribution (0=Female, 1=Male)")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(
    x='Income',
    y='SpendingScore',
    hue='Gender_Male',
    data=df
)
plt.title("Income vs Spending Score")
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

X = df[['Age', 'Income', 'SpendingScore']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
wcss = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)
plt.figure(figsize=(6,4))
plt.plot(range(1,11), wcss, marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

kmeans_temp = KMeans(n_clusters=5, random_state=42)
labels = kmeans_temp.fit_predict(X_scaled)

silhouette_score(X_scaled, labels)
df['Cluster'] = kmeans.labels_

df.groupby('Cluster').mean()

joblib.dump(kmeans, '/content/drive/MyDrive/kmeans_model.pkl')
kmeans = joblib.load('/content/drive/MyDrive/kmeans_model.pkl')

pip install streamlit

import streamlit as st
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler
import altair as alt

st.title("Mall Customer Segmentation")

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/Mall_Customers.csv')

# Rename columns
df.rename(columns={
    'Annual Income (k$)': 'Income',
    'Spending Score (1-100)': 'SpendingScore',
    'Genre': 'Gender'
}, inplace=True)

# Features
X = df[['Age', 'Income', 'SpendingScore']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Load KMeans model (make sure path is correct)
kmeans = joblib.load('/content/drive/MyDrive/kmeans_model.pkl')

# Predict clusters
df['Cluster'] = kmeans.predict(X_scaled)

# Show top rows
st.write(df.head())

# Colored scatter plot using Altair
chart = alt.Chart(df).mark_circle(size=80).encode(
    x='Income',
    y='SpendingScore',
    color='Cluster:N',   # :N = nominal/categorical
    tooltip=['Age', 'Income', 'SpendingScore', 'Cluster']
).interactive()

st.altair_chart(chart, use_container_width=True)

from flask import Flask, render_template
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler

app = Flask(__name__)

@app.route("/")
def index():
    df = pd.read_csv("Mall_Customers.csv")
    X = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = joblib.load("kmeans_model.pkl")
    df['Cluster'] = model.predict(X_scaled)

    return render_template("index.html", tables=[df.head().to_html()])

if __name__ == "__main__":
    app.run(debug=True)

